name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Si tienes un archivo de requisitos
        # O cualquier otro comando para instalar dependencias de tu lenguaje

    - name: Build
      run: |
        # Comandos para compilar/construir/empaquetar tu solución
        # Ejemplo para Python:
        python hola_mundo.py